- name: Prepara ambiente OpenShift
  hosts: localhost
  tasks:
  - name: Prepara ambiente openshift
    include_role:
      name: openshift
    vars:
      user: "{{ item }}"
      action: "remove"
    with_sequence: start=4 end=20 stride=1 format=user%01d
