kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    deployment.kubernetes.io/revision: '3'
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/scc: restricted-v2
  name: openldap
  namespace: {{ user }}-rhsso
  labels:
    app: openldap
    app.kubernetes.io/component: openldap
    app.kubernetes.io/instance: openldap
    app.kubernetes.io/name: openldap
    app.kubernetes.io/part-of: openldap-2441-centos7-app
    app.openshift.io/runtime-namespace: lixo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openldap
        deployment: openldap
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: openldap
          env:
            - name: LDAP_ADMIN_USERNAME
              value: admin
            - name: LDAP_ADMIN_PASSWORD
              value: adminpassword
            - name: LDAP_USERS
              value: customuser
            - name: LDAP_PASSWORDS
              value: custompassword
            - name: LDAP_ROOT
              value: 'dc=example,dc=org'
            - name: LDAP_ADMIN_DN
              value: 'cn=admin,dc=example,dc=org'
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
          ports:
            - containerPort: 1389
              protocol: TCP
            - containerPort: 1636
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: docker.io/bitnami/openldap
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
